vfio: Enforce docker usage inside the Fedora VM
We need to enforce docker usage inside the Fedora VM otherwise building
Cloud Hypervisor from its scripts would fail terribly due to:
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: statfs /var/run/docker.sock: no such file or directory
```

As, for the VFIO Ci using podman or docker is irrelevant, let's enforce
the docker usage there.

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>